apiVersion: v1
kind: Namespace
metadata:
  name: jenkinsns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkinsns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: dougliu/tiny-jenkins:latest
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins_vol
            - name: dockersock
              mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-vol
          emptyDir: {}
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock  

---

# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: limit-range
#   namespace: jenkinsns
# spec:
#   limits:
#   - default:
#       memory: 1024Mi
#       cpu: 1
#     defaultRequest:
#       memory: 1024Mi
#       cpu: 1
#     type: Container

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkinsns
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: jenkin
    - port: 50000
      targetPort: 50000
      name: jnlp
  selector:
    app: jenkins

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: jenkinsns
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: jenkins
  namespace: jenkinsns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
